abbr -a g git
abbr -a ga 'git add'
abbr -a gaa 'git add --all'
abbr -a gapa 'git add --patch'
abbr -a gb 'git branch'
abbr -a gba 'git branch -a'
abbr -a gbd 'git branch -d'
abbr -a gbD 'git branch -D'
abbr -a gbl 'git blame -b -w'
abbr -a gbnm 'git branch --no-merged'
abbr -a gbr 'git branch --remote'
abbr -a gc 'git commit -v'
abbr -a gc! 'git commit -v --amend'
abbr -a gcn! 'git commit -v --no-edit --amend'
abbr -a gca 'git commit -v -a'
abbr -a gca! 'git commit -v -a --amend'
abbr -a gcan! 'git commit -v -a --no-edit --amend'
abbr -a gcam 'git commit -a -m'
abbr -a gcb 'git checkout -b'
abbr -a gcf 'git config --list'
abbr -a gcl 'git clone --recursive'
abbr -a gclean 'git clean -fd'
abbr -a gpristine 'git reset --hard && git clean -dfx'
abbr -a gco 'git checkout'
abbr -a gcount 'git shortlog -sn'
abbr -a gcp 'git cherry-pick'
abbr -a gcs 'git commit -S'
abbr -a gd 'git diff'
abbr -a gdca 'git diff --cached'
abbr -a gdt 'git diff-tree --no-commit-id --name-only -r'
abbr -a gdw 'git diff --word-diff'
abbr -a gf 'git fetch'
abbr -a gfa 'git fetch --all --prune'
abbr -a gfo 'git fetch origin'
abbr -a gg 'git gui citool'
abbr -a gga 'git gui citool --amend'
abbr -a ggpull 'git pull origin (git_current_branch)'
abbr -a ggpush 'git push origin (git_current_branch)'
abbr -a ggsup 'git branch --set-upstream-to=origin/(git_current_branch)'
abbr -a gpsup 'git push --set-upstream origin (git_current_branch)'
abbr -a gignore 'git update-index --assume-unchanged'
abbr -a gignored 'git ls-files -v | grep "^[[:lower:]]"'
abbr -a gk 'gitk --all --branches &!'
abbr -a gl 'git pull'
abbr -a glg 'git log --stat'
abbr -a glgp 'git log --stat -p'
abbr -a glgg 'git log --graph'
abbr -a glgga 'git log --graph --decorate --all'
abbr -a glgm 'git log --graph --max-count=10'
abbr -a glo 'git log --oneline --decorate'
abbr -a glol 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset"'
abbr -a glola 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --all'
abbr -a gm 'git merge'
abbr -a gmom 'git merge origin/master'
abbr -a gmt 'git mergetool --no-prompt'
abbr -a gmtvim 'git mergetool --no-prompt --tool=vimdiff'
abbr -a gp 'git push'
abbr -a gpd 'git push --dry-run'
abbr -a gpu 'git push upstream'
abbr -a gpv 'git push -v'
abbr -a gr 'git remote'
abbr -a gra 'git remote add'
abbr -a grb 'git rebase'
abbr -a grba 'git rebase --abort'
abbr -a grbc 'git rebase --continue'
abbr -a grbi 'git rebase -i'
abbr -a grbm 'git rebase master'
abbr -a grbs 'git rebase --skip'
abbr -a grep 'grep -I --color=auto'
abbr -a grh 'git reset HEAD'
abbr -a grhh 'git reset HEAD --hard'
abbr -a grmv 'git remote rename'
abbr -a grrm 'git remote remove'
abbr -a grset 'git remote set-url'
abbr -a grt 'cd (git rev-parse --show-toplevel || echo ".")'
abbr -a gru 'git reset --'
abbr -a grup 'git remote update'
abbr -a grv 'git remote -v'
abbr -a gsb 'git status -sb'
abbr -a gsi 'git submodule init'
abbr -a gss 'git status -s'
abbr -a gst 'git status'
abbr -a gsta 'git stash'
abbr -a gstaa 'git stash apply'
abbr -a gstc 'git stash clear'
abbr -a gstd 'git stash drop'
abbr -a gstl 'git stash list'
abbr -a gstp 'git stash pop'
abbr -a gsts 'git stash show --text'
abbr -a gsu 'git submodule update'
abbr -a gts 'git tag -s'
abbr -a gtv 'git tag | sort -V'
abbr -a gunignore 'git update-index --no-assume-unchanged'
abbr -a gup 'git pull --rebase'
abbr -a gupv 'git pull --rebase -v'
abbr -a gwch 'git whatchanged -p --abbrev-commit --pretty=medium'
